zoltan-nz/library-app

- app/components/abc-buttons.js
- app/components/spinner-cube.js
- app/controllers/libraries/index.js
- app/routes/libraries/index.js
- app/styles/app.scss
- app/styles/spinner.scss
- app/templates/components/abc-buttons.hbs
- app/templates/components/spinner-cube.hbs
- app/templates/libraries/index.hbs
- app/templates/libraries/loading.hbs
- app/templates/loading.hbs
> Lesson 7 - Add query params, search field, ABC filters, loading spinners

- package.json
- tests/unit/routes/authors-test.js
Thanks much for putting time and effort into this tutorial!
I would like to start my contribution by backfilling tests. This is the first one.
> add unit tests for authors route

- tests/unit/routes/books-test.js
@zoltan-nz ... more unit tests.
Do you happen to know if the [buggy firebase adapter](https://github.com/zoltan-nz/library-app/blob/master/app/routes/books.js#L55) has been fixed yet? If not, I'll look into it. Thanks.
> add unit tests for books route

- .eslintrc.js
- app/controllers/admin/seeder.js
Eslint rules to [enforce semicolons](https://eslint.org/docs/2.0.0/rules/semi) and [validate indentation](https://eslint.org/docs/2.0.0/rules/indent).
> enforce semi and validate indentation

- app/templates/admin/contacts.hbs
- app/templates/admin/invitations.hbs
- app/templates/admin/seeder.hbs
- app/templates/application.hbs
- app/templates/authors.hbs
- app/templates/books.hbs
- app/templates/components/abc-buttons.hbs
- app/templates/components/library-item-form.hbs
- app/templates/components/library-item.hbs
- app/templates/components/nav-link-to.hbs
- app/templates/components/number-box.hbs
- app/templates/components/seeder-block.hbs
- app/templates/contact.hbs
- app/templates/index.hbs
- app/templates/libraries.hbs
- app/templates/libraries/form.hbs
- app/templates/libraries/index.hbs
Here are the fixes for the template lint errors.
> fix template lint errors

- tests/unit/routes/admin/contacts-test.js
- tests/unit/routes/admin/invitations-test.js
- tests/unit/routes/admin/seeder-test.js
Here are the unit tests for the `admin` routes.
> add unit tests for admin routes

- .travis.yml
- package-lock.json
- package.json
Hmm, I don't see the coverage being reported on the [codacy dashboard](https://app.codacy.com/project/zdebre/library-app/dashboard).
You added the `CODACY_PROJECT_TOKEN` as an env variable to Travis, correct?
> report coverage to codacy

- tests/fixtures/authors.js
- tests/fixtures/book.js
- tests/integration/components/author-select-test.js
- tests/unit/components/author-select-test.js
Here are the unit and integration tests for the `{{author-select}}` component.
> add tests for author-select component

- tests/fixtures/book.js
- tests/fixtures/libraries.js
- tests/integration/components/library-select-test.js
- tests/unit/components/library-select-test.js
Here are the unit and integration tests for the {{library-select}} component.
> add tests for library-select component

- tests/unit/models/author-test.js
- tests/unit/models/book-test.js
- tests/unit/models/library-test.js
Here are the unit tests for the remaining models.
> add tests for models

- tests/unit/components/fader-label-test.js
Here are the unit tests for the `{{fader-label}}` component.
> add tests for fader-label component

- tests/integration/components/seeder-block-test.js
Here are integration tests for the `{{seeder-block}}` component.
> add tests for seeder-block component

- tests/unit/controllers/index-test.js
Unit tests for the `index` controller.
> add tests for index controller

- tests/unit/controllers/libraries/index-test.js
Unit tests for the `libraries/index` controller.
> add tests for library index controller

- app/templates/admin/contacts.hbs
- app/templates/admin/invitations.hbs
- app/templates/admin/seeder.hbs
- app/templates/application.hbs
- app/templates/authors.hbs
- app/templates/books.hbs
- app/templates/contact.hbs
- app/templates/index.hbs
- app/templates/libraries/form.hbs
- app/templates/libraries/index.hbs
Octane 🎉, well done on the upgrade @zoltan-nz !
This PR fixes all template linting errors except for [`no-action`](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-action.md), as I figured those are better handled one component at a time (as you already started.)
> fix template linting errors

- app/controllers/admin/seeder.js
- app/templates/admin/seeder.hbs
- Convert SeederController to class syntax
- Remove action helpers from hbs
> Update SeederController to the latest syntax #49

- app/controllers/authors.js
- app/routes/authors.js
- app/templates/authors.hbs
- tests/unit/controllers/authors-test.js
- tests/unit/routes/authors-test.js
- update to class syntax
- move actions to controller
- update hbs templates
> Fix Authors deprecations #49

- .gitignore
- config/dotenv.js
- config/environment.js
- package.json
- yarn.lock
Safely store Firebase API keys and settings in `.env`.
> store firebase keys in dotenv

- .env-sample
- .gitignore
- README.md
- config/dotenv.js
- config/environment.js
@tkraak sorry, I just realised AUTH_DOMAIN and DATABASE_URL can be custom and unique, different than the project id. So it is probably better to manually copy paste these values from Firebase config.
> Add more env variables to manage custom values, update README

- .travis.yml
- package.json
- yarn.lock
- Upgrade coverage package
- Add back coverage report to external services in CI
> Upgrade ember-cli-code-coverage to latest beta fix #66

- .gitignore
- app/controllers/books.js
- app/models/book.js
- jsconfig.json
- tests/unit/controllers/books-test.js
There is no validation check in the saveBook action at the moment, so I just removed that part from the test.
> Fix Books Controller test

- app/components/spinner-cube.js
- app/models/author.js
- app/models/book.js
- app/models/contact.js
- app/models/invitation.js
- app/models/library.js
- app/routes/about.js
- app/routes/admin/contacts.js
- app/routes/admin/invitations.js
- app/routes/admin/seeder.js
fix #47 
Upgrade the rest of routes and models to the new syntax
> Upgrade routes and models to Octance syntax

- app/components/seeder-block.js
- app/services/seeder.js
- app/templates/admin/seeder.hbs
- package.json
- tests/integration/components/seeder-block-test.js
- tests/unit/services/seeder-test.js
- yarn.lock
@zoltan-nz I thought this might lend itself as a gentle introduction to Ember Concurrency. Thoughts?
> replace seeder actions with Ember Concurrency tasks

- .husky/pre-commit
- package.json
- yarn.lock
> Update Husky to latest
